version: '3'
services:

  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - "./mongo.conf:/etc/mongod.conf:ro"
    ports:
      - "27017:27017"
    command: "mongod -f /etc/mongod.conf"

  dicom:
    container_name: dicom
    image: jodogne/orthanc
    ports:
      - "4242:4242"
      - "8042:8042"
    links:
      - mongodb
    volumes:
      - ./orthanc.json:/etc/orthanc/orthanc.json
    command: "--verbose /etc/orthanc/"
    
  data_warehouse:
    container_name: data_warehouse
    build:
      context: .
      dockerfile: ./data_warehouse/Dockerfile
    links:
      - mongodb
      - dicom
    volumes:
      - ./data_warehouse:/app/data_warehouse
    ports:
      - "5000:5000"
    environment:
      MONGODB_URL: "mongodb://mongodb:27017/data_science_challenge"
      DICOM_URL: "http://dicom:8042"
    command: "/app/data_warehouse/start.sh"
    
  data_science:
    container_name: data_science
    build:
      context: .
      dockerfile: ./data_science/Dockerfile
    links:
      - data_warehouse
      - mongodb
    volumes:
      - ./data_science:/app/data_science
    command: "/app/data_science/start.sh"
